### ISSUE TITLE
Option pour activer/désactiver selectivement le Wifi invité/privé

### ISSUE THREAD

**Issue by benacqui** [rene-d/sysbus#1]
Bonjour,
Il peut être intéressant d'activer ou de désactiver sélectivement le réseau wifi invité ou privé de la livebox.
Par exemple, pour tous les objets connectés de la maison qui peuvent représenter un risque en termes de sécurité pour le reste du réseau (où l'on trouverait par exemple un NAS, des ordinateurs/tablettes, etc) je les connecte plutôt au réseau Invité qui ne peux accéder qu'à internet. Or certains de ces objets (les sondes en particulier) nécessitent une connexion permanente pour uploader leur métriques si bien que l'activation/désactivation globale de tout le wifi de la Livebox (avec -wifion et -wifioff) peut se révéler insuffisante lorsque l'on cherche à éteindre le wifi pendant une absence.

Je vous propose donc d'ajouter les options -privatewifion -privatewifioff -guestwifion -guestwifioff à votre script.
D’après me recherches et mes essais il suffirait d'ajouter les options suivantes dans add_command ou add_single :

        [ "guestwifion", "Active le Wifi invité uniquement", [ "NMC.Guest:set", { "Enable":True } ] ],
        [ "guestwifioff", Désactive le Wifi invité uniquement"", [ "NMC.Guest:set", { "Enable":False } ] ],
        [ "privatewifioff", "Désactive le Wifi privé uniquement", [ "NeMo.Intf.lan:setWLANConfig", {"mibs":{"penable":{"wl0":{"Enable":False,"PersistentEnable":False,"Status":False},"eth6":{"Enable":False,"PersistentEnable":False,"Status":False}},"wlanvap":{"wl0":{},"eth6":{}}}} ] ],
        [ "privatewifion", "Active le Wifi privé uniquement", [ "NeMo.Intf.lan:setWLANConfig", {"mibs":{"penable":{"wl0":{"Enable":True,"PersistentEnable":True,"Status":True},"eth6":{"Enable":True,"PersistentEnable":True,"Status":True}},"wlanvap":{"wl0":{},"eth6":{}}}} ] ],

Je précise que phyton n'est pas du tout mon domaine d'expertise et que c'est la première fois que je propose une évolution dans le cadre d'un projet opensource donc veuillez m'excuser d'avance si la forme de cette demande n'est pas conforme aux standards.

J'en profite pour vous remercier pour votre sysbus qui m'aide beaucoup dans le cadre de ma domotique.

Bonne journé.

**Comment by rene-d** [comment]
Bonjour, merci pour le retour ainsi que la proposition, ça fait plaisir :)

Pas de souci pour enrichir le script. Si je l'ai mis sur github, c'est bien pour partager les informations que j'ai pu glaner et que d'autres personnes puissent contribuer, rajouter des fonctionnalités, etc.

Je rajouterai ces commandes dès que possible.

**Comment by rene-d** [comment]
j'ai poussé le commit https://github.com/rene-d/sysbus/commit/bf7689ce0abe4be75b77d35010d1d436141e8900 qui contient ces ajouts. merci :)
