### ISSUE TITLE
argument -devices

### ISSUE THREAD

**Issue by ddelec24** [rene-d/sysbus#11]
Hello,
depuis quelques temps (1mois je dirais) je n'arrive plus à récupérer la liste des équipements (LB3 fibre), voilà ce que jai testé:
**./sysbus-livebox -devices** ou **./sysbus-livebox Hosts:getDevices**
`erreur: {"result":{"status":null,"errors":[{"error":196618,"description":"Object or parameter not found","info":"getDevices"}]}}`

Cependant je trouve bien mes devices si je fais **./sysbus-livebox Devices:get**
je voulais savoir si c'était normal que la commande précédente ne fonctionne plus?

De mon côté je vais modifier le plugin que j'avais trouvé pour ma box domotique jeedom pour que ça refonctionne, j'ai mieux compris le principe du coup.

**Comment by rene-d** [comment]
Pareil pour moi.
Orange a changé quelque chose dans leur data model.
Pas trop le courage de me replonger dans les méandres de la livebox actuellement... Mais je suis à d'écoute d'une solution, si toutefois elle existe !.

**Comment by ddelec24** [comment]
Hello, c'est principalement un changement de syntaxe des clés, alors j'ai corrigé de mon côté de cette manière, lignes 1350+
je me suis basé sur la commande toujours fonctionnelle: Devices:get

> host['ipAddress'] est maintenant host['IPAddress']
> host['active'] est maintenant host['**A**ctive']
> host['hostName'] est maintenant host['**N**ame']
> host['addresses'] n'existe plus, mais on a toujours host['IPAddress'] directement, donc je ne sais pas pourquoi tu avais une boucle avant, peut etre pour avoir ipv4+ipv6? il y a maintenant un array host['IPv6Address']['Address'] etc contenant les infos ipv6


j'ai rajouté une condition supplémentaire pour filtrer les interfaces (DeviceType et IPAddress non vide).
J'ai fait les changements côtés php sinon je taurais directement mis un correctif, mais ça doit être la même en python.

Si tu veux mon dump sans les infos persos + ma config livebox je peux te filer ça mais ça fait plus de 1000 lignes :octocat:

**Comment by rene-d** [comment]
merci pour l'info. je regarderai probablement ce week-end.
et je te solliciterai pour tester éventuellement ^^

**Comment by rene-d** [comment]
La requête est maintenant sysbus.Hosts.Host:get()

Et la réponse a un peu changé (plus de liste d'adresse comme avant d'où ma boucle je suppose).

Du coup j'ai modifié le programme et la commande -hosts, qui refonctionne. Avec en prime un nom lisible d'interface : par exemple 'Ethernet-Port4' au lieu de 'eth3'.

Mais l'occasion je scruterai plus en détails les changements. Il n'y a plus de /scripts.js notamment, ce qui permettait de savoir les requêtes qu'utilisent les pages d'admin.

**Comment by rene-d** [comment]
Quant à -devices je l'ai remappé sur Devices:get(), ce qui est a plus de sens. Mais ce n'est pas vraiment lisible ;-)

**Comment by rene-d** [comment]
je ferme
