### ISSUE TITLE
LB4 Fibre : SPF throughput

### ISSUE THREAD

**Issue by nono303** [rene-d/sysbus#12]
Bonjour @rene-d et merci pour ce super script !   

Ayant une LB4 fibre, je souhaiterais pourvoir monitorer le flux Internet (équivalent ReceiveBlocks et TransmitBlocks de getDSLStats)
J’ai fouillé sur les forums, toutes les options de sysbus pour voir ce qu’y était disponible mais n’ai malheureusement rien trouvé. Sans succès donc :

-  `sysbus.py -MIBs eth0` (cf. [mibs.eth0.txt](https://github.com/rene-d/sysbus/files/2868897/mibs.eth0.txt))
   -  `StatMon Enable: False` mais je n’ai pas trouvé de methode pour l’activer
-  `sysbus.py -model`
   -  `vlan_data` ; rien
   -  `vlan_multi` ; rien
   -  `SFP` ; rien
   -  `getStats` ; uniquement pour `sysbus.NMC.Wifi`
   -  `Rx, Tx, Packets, Blocks` ; rien

Bref, Aurais-tu des pistes à me proposer pour arriver à mes fins ?

Merci d’avance !

++NoNo

**Comment by rene-d** [comment]
Salut,
Merci :) 
J'avais un peu cherché il y a quelques temps, sans succès probant.
Je reregarderai, les MIB ont un peu changé depuis l'écriture du script.

**Comment by rene-d** [comment]
J'ai donc regardé... rien de probant. Les informations qu'on peut trouver sont grosso modo celles accessibles via l'interface d'administration. Et il n'y a pas d'info de trafic internet (ou alors je ne les ai pas trouvées).

**Comment by nono303** [comment]
Idem de mon coté :(
Merci du retour !

**Comment by p-dor** [comment]
Hello, si cela peut en aider certains, la bonne API à utiliser est celle ci, pour toutes les interfaces :
`NeMo.Intf._MIB_:getNetDevStats`

Donc pour la LB4, le traffic internet peut être mesuré avec :
`NeMo.Intf.eth0:getNetDevStats`

Un exemple de mise en oeuvre ici :
https://github.com/p-dor/LiveboxMonitor

**Comment by rene-d** [comment]
Hello, j'ai vu ton programme, après l'article publié par https://macg.co :) Bravo ! Et merci de m'avoir cité.

**Comment by rene-d** [comment]
Quant à ce dépôt/script, il n'est probablement plus tellement à jour... 😕

**Comment by p-dor** [comment]
Peut être mais sans celui ci je pense que je n'aurai jamais eu le courage dans me lancer dans mon propre projet... donc merci à toi d'avoir mis tout ça au service de la communauté !
Et j'utilise sysbus toujours énormément dans mes recherches... cela reste extrêmement utile à beaucoup de monde !
