### ISSUE TITLE
reboot livebox

### ISSUE THREAD

**Issue by F-PMOR** [rene-d/sysbus#13]
Bonjour René,
Ce n'est pas un problème mais une simple question, je ne sais pas ou poser ma question.... :-(
Avant d'utiliser ton code. Est ce possible d'envoyer une commande de reboot (ex: si on voit que la connexion ADSL n'est pas up ?) ?
En te remerciant d'avance,
Philippe

**Comment by etieng** [comment]
Bonjour,
`$ ./sysbus.py sysbus.NMC:reboot`

PS: Je me sert du merveilleux travail de René pour rebooter ma livebox toute les nuits à 2h du matin (réinitialiser DLM) et récupérer un peu de debit.
Je m'en sert aussi pour monitorer dans Munin le débit de la ligne (DLM).

Au plaisir

**Comment by rene-d** [comment]
@F-PMOR : je ne suis pas sûr qu'il y ait un autre endroit pour discuter sur GitHub. 
@etieng  : merci ^^

rené

**Comment by F-PMOR** [comment]
Merci à vous ;-)
je viens donc d'installer sysbus sous centos7 (donc dans un venv avec python 3).
et j'ai l'erreur suivante.. si vous avez une idée (pi, je commence avec python...).
(p3) [root@PCS21 p3]# sysbus/sysbus.py
Traceback (most recent call last):
  File "sysbus/sysbus.py", line 1966, in <module>
    main()
  File "sysbus/sysbus.py", line 1927, in main
    if not auth(new_session):       # initialise la session requests avec authentification
  File "sysbus/sysbus.py", line 288, in auth
    if not 'contextID' in r.json()['data']:
  File "/root/p3/bin/p3/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rene-d** [comment]
il faut s'authentifier avant de passer une commande (sans option, ça affiche le statut).

pas très ergonomique j'avoue.

mais ce projet était à la base une exploration de la livebox, et ça l'est plus ou moins resté :)

**Comment by F-PMOR** [comment]
j'ai bien tenté de faire l'authentification mais ça ne marche toujours pas. j'avais bien créé le fichier de conf via option config comme indiqué dans ton readme.
Pour info, je suis en virtuelenv avec python 3.6 sous Centos 7. J'ai simplement installé requests dans les lib.

voici les traces (j'ai bien mis le bon mdp que j'ai modifié dans la trace ci-dessous)


(p3) [root@PCS21 sysbus]# ./sysbus.py -user admin -password password -url http://192.168.1.1
Traceback (most recent call last):
  File "./sysbus.py", line 1966, in <module>
    main()
  File "./sysbus.py", line 1927, in main
    if not auth(new_session):       # initialise la session requests avec authentification
  File "./sysbus.py", line 288, in auth
    if not 'contextID' in r.json()['data']:
  File "/root/p3/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

si tu as une idée.

merci d'avance,
Philippe

**Comment by rene-d** [comment]
Je regarderai ce soir
Rene 

Envoyé de mon iPhone

**Comment by F-PMOR** [comment]
René, ça marche maintenant, pb de proxy de mon coté je pense ;-)
Merci beaucoup.

**Comment by F-PMOR** [comment]
Ca marche ;-) j'ai testé sur Windows et maintenant sur linux aussi.. pb de proxy... merci bcp
