### ISSUE TITLE
[add feature] -wpspairingoff

### ISSUE THREAD

**Issue by mabed-fr** [rene-d/sysbus#16]
Ajout feature STOP pour le pairing WPS

j'ai testé cela:
./sysbus.py sysbus.NMC.Wifi:stopPairing

Cela fonctionne parfaitement.

Trouvé à partir de ce modèle

OBJECT NAME: 'NMC.Wifi' (name: Wifi)
function: startPairing (opt clientPIN)
function: stopPairing ()
function: startAutoChannelSelection ()
function: getStats (out RxBytes, out TxBytes)
function: get ()
function: set (opt parameters)

**Comment by mabed-fr** [comment]
Après analyse du code je pense qu'il faudrait rajouter:`

[ "wpspairingon", "", "sysbus.NMC.Wifi:stopPairing"],`

Dans la section approprié et modifier l'output de la commande qui n'ait pas très explicite .

**Comment by rene-d** [comment]
salut, si tu veux que les commandes que tu as ajoutées soient intégrées, il faut faire une Pull Request
