### ISSUE TITLE
Valeurs affichées en Mibit au lieu de Mbit

### ISSUE THREAD

**Issue by Rpnpif** [rene-d/sysbus#2]
Les valeurs affichées sont en Mibit (1024 bits) et pas en Mbit (1000 bits) qui est l'unité mentionnée derrière la valeur suite à la commande dslrate.

Voir https://fr.wikipedia.org/wiki/Préfixe_binaire et https://fr.wikipedia.org/wiki/Mégabit

Merci pour ce programme.

**Comment by Rpnpif** [comment]
Bien sûr, il s'agit respectivement de 1024 Kibits et de 1000 kbits.

**Comment by rene-d** [comment]
Le mégabit est toujours plus répandu que le mébibit, même si c'est sémantiquement inexact. Il n'y a guère que les constructeurs de disque dur pour utiliser un facteur en 10^3 au lieu de 2^10...

**Comment by Rpnpif** [comment]
Cela dépend du secteur d'activité, je suppose. En 2017, les programmes sous Linux utilisent très majoritairement la valeur normalisée du mégabit (10^6) ou le mébibit (2^20) (ou le kbit/kibibit). Les pages de manuel incluses dans les distributions Linux sont aussi mises à jour depuis au moins 5 ans. C'est aussi vrai pour la plupart des gros logiciels nouvellement développés. Utiliser les versions ISO ou SI de ces unités évite les confusions et malentendus.
