### ISSUE TITLE
Modification des identifiants FTI

### ISSUE THREAD

**Issue by JulienWgr** [rene-d/sysbus#27]
Bonjour,
Est-il possible avec le script de modifier les identifiants FTI/passwd ?
Je suis très intéressé par cet option, si possible d'en faire une réalèse ? Sinon je veux bien contrib mais j'ai pas encore trouvé comment le faire ! 🤨

Merci à vous.

**Comment by rene-d** [comment]
salut,
je ne sais pas trop, je ne change jamais mes identifiants FTI :)
mais oui ça doit être possible. deux solutions pour trouver comment faire: soit en devinant à l'aide de la MIB, soit en enregistrant avec wireshark une session où on modifie ces identifiants.
