### ISSUE TITLE
New API for Livebox Pro 4?

### ISSUE THREAD

**Issue by fozog** [rene-d/sysbus#3]
Looks like the new LB Pro has a new API.

Login is done with: 
HTML Form URL Encoded: application/x-www-form-urlencoded
Form item: "req" = "{"request":{"id":1,"session-id":23,"priority":false,"actions":[{"id":0,"method":"getValue","xpath":"Device/UserAccounts/ManagedUsers/ManagedUser[Login='admin']/SecretQuery"}],"cnonce":1606464506,"auth-key":"540b758bed93

I can attach full capture if needed.

**Comment by rene-d** [comment]
Hello fozog,

This script is not intended for the Livebox Pro, neither the new nor the old ones. I would be surprised if they use the same kind of management API.

You are welcome if you want to write something around the LB Pro ;-)

**Comment by cyayon** [comment]
I have the same issue with a livebox pro 4.

a solution to have ADSL stats with a script ? 

thanks.

**Comment by rene-d** [comment]
sysbus.py est incompatible avec les Livebox Pro.
A ma connaissance, leur logiciel n'utilise pas ce système.
