### ISSUE TITLE
Livebox 5 reboot

### ISSUE THREAD

**Issue by josephernest** [rene-d/sysbus#34]
Merci pour ce repo utile!

Auriez-vous une info sur comment rebooter une Livebox 5 ?

L'URL `http://192.168.1.1/authenticate?username=admin&password=...` donne une réponse 404.

**Comment by rene-d** [comment]
L'authentification est un peu plus compliquée que ça. le script le fait, et doit pouvoir reboot une lb5 (mais je ne sais plus exactement quelle commande)

**Comment by josephernest** [comment]
Ce projet gère-t-il les LB5? Partout dans les docs de ce repo et sur http://rene-d.github.io/sysbus/ il est indiqué LB2, 3 et 4, donc je n'étais pas sûr.
A quel endroit dans votre code se fait l'auth sur une LB5?
Aux alentours de https://github.com/rene-d/sysbus/blob/master/src/sysbus/sysbus.py#L284 je trouve essentiellement les LB4.

Merci à vous!

**Comment by rene-d** [comment]
je n'ai pas mis à jour le script et le readme pour les lb5 mais ça fonctionne. l'auth est la même que pour les lb4

**Comment by josephernest** [comment]
Merci! Auriez-vous le lien vers la ligne du source où se fait l'auth pour LB4?

**Comment by rene-d** [comment]
https://github.com/rene-d/sysbus/blob/04bd790dd33f1d3907f059a42526b3985fbaaaa2/src/sysbus/sysbus.py#L291

**Comment by josephernest** [comment]
Merci @rene-d. L'auth fonctionne en effet, je viens de tester. Par contre le reboot ne fonctionne pas:

```
import requests
session = requests.Session()
auth = '{"service":"sah.Device.Information","method":"createContext","parameters":{"applicationName":"so_sdkut","username":"admin","password":"mypassword"}}'
sah_headers = {'Content-Type': 'application/x-sah-ws-1-call+json', 'Authorization': 'X-Sah-Login'}
r = session.post('http://192.168.1.1/ws', data=auth, headers=sah_headers)
contextID = r.json()['data']['contextID']
sah_headers = {'X-Context': contextID, 'X-Prototype-Version': '1.7', 'Content-Type': 'application/x-sah-ws-1-call+json; charset=UTF-8', 'Accept': 'text/javascript'}
r = session.post('http://192.168.1.1/sysbus/Time:getTime', headers=sah_headers, data='{"parameters":{}}')
print(r.json())  # {'result': {'status': True, 'data': {'time': 'Sat, 23 Apr 2022 19:40:08 GMT+0200'}}}
r = requests.post("http://192.168.1.1/sysbus/NMC:reboot", headers=sah_headers, data='{"parameters":{}}')
print(r.json())  # {'result': {'status': None, 'errors': [{'error': 13, 'description': 'Permission denied', 'info': 'NMC'}]}}
```

Une idée pourquoi `http://192.168.1.1/sysbus/NMC:reboot` ne fonctionne pas sur Livebox 5? Merci!
