### ISSUE TITLE
auth invalid syntax

### ISSUE THREAD

**Issue by jec44** [rene-d/sysbus#4]
Bonjour, 
J'ai un petit soucis lorsque je lance le script pour initialiser le password :
File "./sysbus.py", line 274
    auth =
          ^
SyntaxError: invalid syntax

Alors j'ai modifié le mot de passe manuellement dans le script mais pas mieux.
J'ai une livebox 4 avec le dernier Firmeware 2.20.10 (g0-f-sip-fr)

J'utilise Domoticz chez moi, mon but est de récupérer les devices connectés à la livebox pour déclencher dans Domoticz des devices et ainsi pouvoir mettre la maison sous alarme (ou pas)
Merci de votre aide.

**Comment by rene-d** [comment]
Bonsoir,

Je pense que tu as modifié malencontreusement le script. Cette [ligne 274](https://github.com/rene-d/sysbus/blob/master/sysbus.py#L274) est un peu plus longue que "auth ="...  

N'aurais-tu pas fait un copier/coller depuis le navigateur dans un éditeur de texte ?

Pour télécharger le script, si on n'utilise pas git, la meilleure solution est encore d'utiliser wget ou curl :
      `wget https://raw.githubusercontent.com/rene-d/sysbus/master/sysbus.py`
ou  
      `curl -O https://raw.githubusercontent.com/rene-d/sysbus/master/sysbus.py`
puis le rendre exécutable :
   `chmod a+x sysbus.py`
