### ISSUE TITLE
[feature request] new way to display calls

### ISSUE THREAD

**Issue by solsticedhiver** [rene-d/sysbus#5]
I have patched sysbus.py to get calls in chronological order and add an arrow to know if it's an incoming or outgoing call

    @@ -1730,14 +1736,19 @@ def add_commands(parser):
             if len(args) == 1 and args[0] == '?':
                 return print(r[0].keys())
     
    -        for i in reversed(r):
    +        for i in r:
                 if len(args) > 0:
                     print(i[args[0]])
                 else:
                    d = datetime.datetime.strptime(i['startTime'], "%Y-%m-%dT%H:%M:%SZ")
 
    -                print("{:>3} {:12}   {}  {}   {:10}".format(
    +                if i['callOrigin'] == 'local':
    +                    arrow = '<=='
    +                else:
    +                    arrow = '==>'
    +                print("{:>3} {} {:12}  {}  {}  {:10}".format( 
                         i['callId'],
    +                    arrow,
                         i['remoteNumber'],
                         d,
                         str(datetime.timedelta(seconds=int(i['duration']))),

**Comment by rene-d** [comment]
Merci. Je vais tester cela.

**Comment by rene-d** [comment]
j'aurais plutôt mis les flèches dans l'autre sens, mais admettons :)
