### ISSUE TITLE
 [feature request] consistent order of model output

### ISSUE THREAD

**Issue by solsticedhiver** [rene-d/sysbus#6]
I have made that one line change to get sorted output on the model key name.

```
@@ -517,7 +523,7 @@ def model(node, level=0, file=None):
             print("-->", i, len(node[i]), file=file)
 
     if 'children' in node:
-        for c in node['children']:
+        for c in sorted(node['children'], key=lambda o:o['objectInfo']['key']):
             model(c, level + 1, file=file)

```
This way, the model output is (almost) always the same. And one can do diff from a previous output to the current one.

This is a very minor change for every day user. Just fits my needs.

**Comment by rene-d** [comment]
You can fork the project and make a pull request ;-)

Thanks again for your interest !


PS: je ne sais pas s'il y a d'autres personnes que des francophones intéressés par ce projet ;-)

**Comment by rene-d** [comment]
En fait, je pense qu'il est plus consistant de garder l'ordre du data model. Cependant, je comprends qu'un besoin particulier requiert un tri.
