### ISSUE TITLE
[feature request] explicit show that number is mask/hidden

### ISSUE THREAD

**Issue by solsticedhiver** [rene-d/sysbus#7]
On `-call` output, show an explicit string that shows that incoming number is masked/hidden instead of ''

Could be anything from `Masked` or `Hidden` or `**********`. The last one being my favorite.

line 1746 becomes:

              i['remoteNumber'] if i['remoteNumber'] != '' else '**********',

**Comment by rene-d** [comment]
Bizarre, je n'ai aucun appel avec un remoteNumber vide. A la place, j'ai "Private".
Peut-être une version différente du firmware. Je suis en SG40_sip-fr-3.4.10.1_7.21.3.1

J'ai cependant intégré la modification.

**Comment by solsticedhiver** [comment]
C'est une Livebox 3.

Au passage, j'ai du changer en dur dans le script VERSION_LIVEBOX en lb28 pour que ça marche. Je sais pas si c'est ça qu'il fallait faire.
