### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by lolo100090** [rene-d/sysbus#8]
Bonjour,
j'ai mis le script sur un serveur Alcasr : chez moi le script de rédemarre bien ma box orange 4 fibre (perso), mais là où ilest installé, il n'arrive pas à redémarrer la box orange pro V4 ; 
message d'erreur : 
`Traceback (most recent call last):
  File "./sysbus.py", line 1924, in <module>
    main()
  File "./sysbus.py", line 1885, in main
    if not auth(new_session):       # initialise la session requests avec authentification
  File "./sysbus.py", line 280, in auth
    if not 'contextID' in r.json()['data']:
  File "/root/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Quelqu'un a-t-il déjà rencontré le pb ...?
Merci

**Comment by lolo100090** [comment]
Ah oui donc, pour finir mon message, quelqu'un a-t-il déjà rencontré le pb ...? 
Merci

**Comment by rene-d** [comment]
Attention, la Livebox Pro utilise une API différente, d'après ce que je sais. Du coup ce programme est certainement inutilisable :(

**Comment by lolo100090** [comment]
Ah zut ... 
et donc du coup t'as des conseils ou des pistes à explorer pour que j'adapte ton script ?

**Comment by rene-d** [comment]
Des pistes non... je n'ai jamais utilisé ni même vu de lb pro. Je *suppose* que les premiers modèles étaient des projets entièrement disjoints de ceux destinés au grand public. C'est peut-être toujours le cas, ou pas.

Des conseils, peut-être, mais il faut mettre les mains dans le cambouis, creuser et imaginer un peu ! Par exemple, tu peux toujours te connecter sur l'interface d'administration et regarder avec ton navigateur (ou Wireshark si tu es courageux et si ce n'est pas en https) les échanges avec la livebox. S'il y a une appli sur smartphone, tu peux utiliser un logiciel du genre [Charles Proxy](https://www.charlesproxy.com) ou [Fiddler](https://www.telerik.com/fiddler).

**Comment by cyayon** [comment]
pareil...
si qqun a des nouvelles, je suis preneur ...
